// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace Noisewall
{
    public class NoisewallOutputs: ResultsBase
    {
		/// <summary>
		/// The number of noisewall panels
		/// </summary>
		[JsonProperty("Panel Count")]
		public double PanelCount {get;}



        /// <summary>
        /// Construct a NoisewallOutputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public NoisewallOutputs() : base()
        {

        }


        /// <summary>
        /// Construct a NoisewallOutputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public NoisewallOutputs(double panelCount): base()
        {
			this.PanelCount = panelCount;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}